__version__: str

def normalize_text(text: str) -> str: ...
def repair_hyphenation(text: str) -> str: ...
def detect_language(text: str) -> tuple[str, str, float]: ...
def numbering_info(line: str) -> tuple[str, int] | None: ...
def split_sentences(text: str) -> list[str]: ...
def estimate_tokens(text: str) -> int: ...
