__version__: str

def normalize_text(text: str) -> str: ...
def normalize_text_stats(text: str) -> tuple[str, int, int, int]: ...
def map_symbol_font(text: str, font_name: str) -> tuple[str, int, int]: ...
def repair_hyphenation(text: str) -> str: ...
def detect_language(text: str) -> tuple[str, str, float]: ...
def numbering_info(line: str) -> tuple[str, int] | None: ...
def set_heading_keywords(keywords: list[tuple[str, int]]) -> None: ...
def split_sentences(text: str) -> list[str]: ...
def estimate_tokens(text: str) -> int: ...

class Hyphenator:
    def __init__(self, keep: list[str]) -> None: ...
    def repair(self, text: str) -> str: ...
